table Fact_Sales
	lineageTag: 6e636ee0-08f7-428a-b7cd-41f6da288112

	measure 'Total Sales' = SUM(Fact_Sales[sales_amount])
		lineageTag: 9eefb162-99b8-4e47-acba-fed15edff7bb

	measure 'MoM Sales Growth %' = ```
			VAR CurrentSales = [Total Sales]
			VAR PreviousMonthSales =
				CALCULATE(
					[Total Sales],
					DATEADD('Dim_Date'[date], -1, MONTH)
				)
			RETURN
				DIVIDE(CurrentSales - PreviousMonthSales, PreviousMonthSales)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ebce09e9-5303-477e-8d44-e970e461ac34

	measure 'Running Total Sales' =
			CALCULATE(
				[Total Sales],
				FILTER(
					ALL('Dim_Date'[date]),
					'Dim_Date'[date] <= MAX('Dim_Date'[date])
				)
			)

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: f65a7e7a-fee8-452c-9a6b-a3d4133de320
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cd1b0785-4a99-4985-a167-7b8e7527dcb8
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 25064fec-f3bb-4110-b6b0-9e41aa31ce04
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 55c3d0ff-c57d-4246-a8e8-fc47e2514b9a
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 4dd63f28-cf17-4c46-b2d0-3958106e4b38
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 8908a049-7934-4343-b0b3-b5573319e4ed
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: ad4de7a7-a95d-48a2-880b-d7e997730eb7
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 2e0df203-c850-4e94-bd4b-f6cddb29ec22
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 92efaa95-031e-42c3-a971-c99423f0b7e8
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductKey
		dataType: string
		lineageTag: 2603ba12-777d-497f-98d1-8d31e353d94d
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Alex Roshni Angel\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "ProductKey", each [category] & "-" & [item]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"ProductKey", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

